# Site settings
title: Josh Sim's Software Engineering Portfolio
email: simjd1@student.op.ac.nz
description: Portfolio for Software Engineering
baseurl: "/SoftwareEngineeringPortfolio"
url: "https://jimmayx.github.io/"

author:
  name     : 'Josh Sim'
  email    : simjd1@student.op.ac.nz
  url      : https://jimmayx.github.io/
  facebook : http://facebook.com/XxJimmayxxX
  twitter  : http://twitter.com/jimmayx

github: https://github.com/jimmayx

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
